[package]
authors = ["statiolake <statiolake@gmail.com>"]
name = "procon-assistant"
version = "0.1.0"
edition = "2018"

[dependencies]
clipboard = "0.5.0"
dirs = "2.0.1"
encoding = "0.2.33"
percent-encoding = "1.0.1"
regex = "1.1.6"
reqwest = "0.9.17"
rpassword = "3.0.2"
scraper = "0.10.0"
serde = "1.0.91"
serde_derive = "1.0.91"
serde_json = "1.0.39"
time = "0.1.42"
lazy_static = "1.3.0"
atty = "0.2.11"
which = "2.0.1"
current_exe = { git = "https://github.com/statiolake/current-exe-rs" }
to_absolute = { git = "https://github.com/statiolake/to-absolute-rs" }
anyhow = "1.0.26"
thiserror = "1.0.11"

[dependencies.colored_print]
git = "https://github.com/statiolake/colored_print.git"
