[package]
authors = ["statiolake <statiolake@gmail.com>"]
name = "procon-assistant"
version = "0.1.0"

[dependencies]
clipboard = "0.4.6"
isatty = "0.1.6"
percent-encoding = "1.0.1"
regex = "0.2.10"
reqwest = "0.8.5"
rpassword = "2.0.0"
scraper = "0.6.0"
serde = "1.0.55"
serde_derive = "1.0.55"
serde_json = "1.0.17"
time = "0.1.39"

[dependencies.colored_print]
git = "https://github.com/statiolake/colored_print.git"
