[package]
authors = ["statiolake <statiolake@gmail.com>"]
name = "procon-assistant"
version = "0.1.0"
edition = "2018"

[dependencies]
clipboard = "0.5.0"
dirs = "1.0.4"
encoding = "0.2.33"
percent-encoding = "1.0.1"
regex = "1.0.5"
reqwest = "0.9.2"
rpassword = "2.0.0"
scraper = "0.7.0"
serde = "1.0.79"
serde_derive = "1.0.79"
serde_json = "1.0.32"
time = "0.1.40"
lazy_static = "1.1.0"
atty = "0.2.11"
which = "2.0.0"

[dependencies.colored_print]
git = "https://github.com/statiolake/colored_print.git"
